[
  ["mqtt", "o", {title: "MQTT settings"}],
  ["mqtt.server", "s", "cloud.mongoose-iot.com:1883", {title: "MQTT server"}],
  ["mqtt.reconnect_timeout_min", "i", 10, {title: "Starting reconnect timeout"}],
  ["mqtt.reconnect_timeout_max", "i", 60, {title: "Maximum reconnect timeout"}],
]
