[
  ["rpc.ws", "o", {title: "RPC over WebSocket settings"}],
  ["rpc.ws.enable", "b", true, {title: "Enable RPC over WebSocket"}],
  ["rpc.ws.server_address", "s", "", {title: "Cloud server address"}],
  ["rpc.ws.reconnect_interval_min", "i", 1, {title: "Minimal reconnect interval"}],
  ["rpc.ws.reconnect_interval_max", "i", 60, {title: "Maximal reconnect interval"}],
  ["rpc.ws.ssl_server_name", "s", {title : "TLS Server Name"}],
  ["rpc.ws.ssl_ca_file", "s", {title : "TLS CA file"}],
  ["rpc.ws.ssl_client_cert_file", "s", {title: "TLS client cert file"}],
]
