[
  ["aws", "o", {title: "AWS settings"}],
  ["aws.shadow", "o", {title: "AWS Device Shadow settings"}],
  ["aws.shadow.enable", "b", false, {title: "Enable AWS Device Shadow"}],
  ["aws.shadow.get_on_connect", "b", true, {title: "Request state on (re)connect"}],
]
