[
  ["device", "o", {title: "Device settings"}],
  ["device.id", "s", {title: "Device ID"}],  # Note: Each arch defines a default
  ["device.password", "s", {title: "Device password"}],

  ["debug", "o", {title: "Debug Settings"}],
  ["debug.level", "i", 2, {
    title: "Level",
    type: "select",
    values: [
      {value: -1, title: "NONE"},
      {value: 0, title: "ERROR"},
      {value: 1, title: "WARN"},
      {value: 2, title: "INFO"},
      {value: 3, title: "DEBUG"},
      {value: 4, title: "VERBOSE_DEBUG"}
    ]
  }],
  ["debug.filter", "s", {title: "Log filter against source file name or function name. Comma separated list of prefix match glob patterns, e.g. *mqtt*,mgos_wifi"}],
  ["debug.stdout_uart", "i", {title: "STDOUT UART (-1 to disable)"}],
  ["debug.stderr_uart", "i", {title: "STDERR UART (-1 to disable)"}],
  ["debug.factory_reset_gpio", "i", -1, {title: "Factory reset GPIO (low on boot)"}],
  ["debug.mg_mgr_hexdump_file", "s", {title: "File name to hexdump network traffic to. Use '-' for stdout, '--' for stderr."}],

  ["sys", "o", {title: "System settings"}],
  ["sys.mount", "o", {title: "Extra filesystem to mount"}],
  ["sys.mount.path", "s", "", {title: "Mount point"}],
  ["sys.mount.dev_type", "s", "", {title: "Storage device type"}],
  ["sys.mount.dev_opts", "s", "", {title: "Storage device options"}],
  ["sys.mount.fs_type", "s", "", {title: "Filesystem type"}],
  ["sys.mount.fs_opts", "s", "", {title: "Filesystem options"}],
  ["sys.tz_spec", "s", "", {title: "See formats for the TZ env var: \"man tzset\". Formats like \":/path/to/file\" are not supported"}],
  ["sys.wdt_timeout", "i", 30, {title: "Watchdog timeout (seconds)"}],
  ["sys.pref_ota_lib", "s", {title: "Preferred ota lib, e.g. dash, ota-http-client"}],

  ["conf_acl", "s", "*", {title: "Conf ACL"}],
]
